on: issues
name: Template Variables in Markdown
jobs:
  markdown:
    name: markdown-marker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: bdougie/variables-in-markdown@master
      env:
        IOFSVersion: ${{ 2.3.1 }}
