name: Dynamic Template

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  markdown:
    name: "Update Templates"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: bdougie/variables-in-markdown@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
